### ISSUE TITLE
Colors on Settings

### ISSUE THREAD

**Issue by chow1026** [cityjson/ninja#6]
It's very nice feature to allow user to set colors they want in the settings. Is it possible to add color picker so user doesn't have to look up for HEX code for the color to fill in the form? 

![ColorPicker](https://user-images.githubusercontent.com/16604634/78765564-c12c3800-79ba-11ea-914c-0bd73b4c327b.png)

It is also noted that the label/name is somewhat hard to see with the grey background. Is it better that the HEX code is shown in the color it represents itself?

**Comment by liberostelios** [comment]
Fixed in v0.5.0
