### ISSUE TITLE
Visualizing LoDs

### ISSUE THREAD

**Issue by ozgetufan** [cityjson/ninja#66]
When objects have multiple LoDs, it is not possible to select each representation separately, but the objects are shown in highest LoD (at least in my case). It would be nice to be able to enable/disable different LoDs. 

![image](https://user-images.githubusercontent.com/71127957/149525655-dd5212f4-8681-411e-90fc-bc9279e3146d.png)

**Comment by liberostelios** [comment]
Fixed with 9bf4704e90c45805d62785231eaeeb4d35a1331d
